---
# tasks file for bx_push_server
- name: Install push-server
  ansible.builtin.include_tasks: install.yml
  when: bx_push_server_action == "INSTALL"

- name: Remove push-server
  ansible.builtin.include_tasks: remove.yml
  when: bx_push_server_action == "DELETE"
