location = /robots.txt {
    error_page 404 /404.html;
    access_log   off;
    log_not_found off;
}

### examples
#location = /robots.txt {
#     try_files   /robots/robots_$host.txt /robots.txt =404;
#}


# location = /robots.txt {
### not main domain
#    if ($http_host != domain.tld) {
#        rewrite ^/robots.txt /robots_mp.txt last;
#    }

### default
# try_files /robots.txt =404;
# }

###
# location ~* ^/sitemap(.*)\.xml {
#    try_files  /sitemap/$host/$request_uri /$request_uri =404;
#}
