# https://yandex.ru/support/metrica/code/install-counter-csp.html#install-counter-csp__urls
# http://alexvaleev.ru/webvisor-bitrix/
set $frame_options '';
      if ($http_referer !~ '^https?:\/\/([^\/]+\.)?(webvisor\.(com|org)|metri[ck]a\.yandex\.(com|ru|az|by|co\.il|com\.am|com\.ge|com\.tr|ee|fr|kg|kz|lt|lv|md|tj|tm|uz))\/'){
          set $frame_options 'SAMEORIGIN';
      }
add_header X-Frame-Options $frame_options;

if_modified_since     before;

# add slash
set $add_slash 1;

# Check if the URI already ends with a slash; if so, disable adding a slash
if ($uri ~ /$) {
    set $add_slash 0;
}
if ($uri ~ \.) {
    set $add_slash 0;
}
if ($is_args) {
    set $add_slash 0;
}
if (-e $request_filename) {
  set $add_slash 0;
}
if ($request_uri ~ "^/bitrix/admin") {
  set $add_slash 0;
}
if ($request_uri ~ "^.*/index.php?") {
  set $add_slash 0;
}
if ($request_uri ~ "^/upload/documentgenerator") {
  set $add_slash 0;
}
if ($request_uri ~ "^/upload/") {
  set $add_slash 0;
}
if ($request_uri ~ "^/personal") {
  set $add_slash 0;
}
if ($request_uri ~ "^/basic_status") {
  set $add_slash 0;
}
if ($request_uri ~ "^/php_fpm_status") {
  set $add_slash 0;
}
if ($request_uri ~ "^/fpmstatus.php") {
  set $add_slash 0;
}
if ($request_uri ~ "^/ping") {
  set $add_slash 0;
}
if ($request_method != GET) {
    set $add_slash 0;
}
# Redirect if $add_slash is 1 and URI does not end with a slash
if ($add_slash = 1) {
    return 308 $uri/$is_args$args;
}


# Remove Trailing Question Mark
#if ($request_uri ~ ^(/(?!personal|bitrix|auth).*)\?$) { return 308 $1/$is_args$args; }

# Remove Trailing /%20/
#if ($request_uri ~ ^(.*)\/%20\/$) { return 308 $1/$is_args$args; }

# remove index.php|html
if ($request_uri ~ ^([^\?]*)/index\.(html|php)) { return 308 $1/$is_args$args; }
