---
- name: Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family | lower == "debian"

- name: RedHat>7
  ansible.builtin.include_tasks: redhat.yml
  when:
    - ansible_os_family | lower == "redhat"
    - ansible_distribution_major_version >= '8'

- name: RedHat 7
  ansible.builtin.include_tasks: redhat7.yml
  when:
    - ansible_os_family | lower == "redhat"
    - ansible_distribution_major_version == '7'

- name: Apt update and install Crowdsec
  ansible.builtin.package:
    update_cache: false
    name: crowdsec
    state: present

- name: Crowdsec-firewall-bouncer-nftables
  ansible.builtin.package:
    update_cache: false
    name: crowdsec-firewall-bouncer-nftables
    state: present
  when:
    - crowdsec_install_firewall_bouncer | bool
    - ansible_os_family | lower == "debian"

- name: Crowdsec-firewall-bouncer-iptables
  ansible.builtin.package:
    update_cache: false
    name: crowdsec-firewall-bouncer-iptables
    state: present
  when:
    - ansible_os_family | lower == "redhat"
    - ansible_distribution_major_version == '7'
    - crowdsec_install_firewall_bouncer | bool

# Update / upgrade
- name: Cscli hub update
  ansible.builtin.command:
    cmd: cscli hub update
  changed_when: false

- name: Cscli hub upgrade
  ansible.builtin.command:
    cmd: cscli hub upgrade
  register: hub_upgrade_result
  changed_when: false

# collections
- name: Crowdsec - remove collections
  ansible.builtin.command:
    cmd: "cscli collections remove {{ item }}"
  with_items: "{{ cs_collections_remove_list }}"
  register: collections_remove_result
  changed_when: "'systemctl reload crowdsec' in collections_remove_result.stderr"
  when: cs_collections_remove_list | length > 0

- name: Crowdsec - install collections
  ansible.builtin.command:
    cmd: "cscli collections install {{ item }}"
  with_items: "{{ cs_collections_list }}"
  register: collections_install_result
  changed_when: "'overwrite' not in collections_install_result.stderr"
  when: cs_collections_list | length > 0


# scenarios
- name: Crowdsec - remove scenarios
  ansible.builtin.command:
    cmd: "cscli scenarios remove {{ item }}"
  with_items: "{{ cs_scenarios_remove_list }}"
  register: scenarios_remove_result
  changed_when: "'systemctl reload crowdsec' in scenarios_remove_result.stderr"
  when: cs_scenarios_remove_list | length > 0

- name: Crowdsec - install scenarios
  ansible.builtin.command:
    cmd: "cscli scenarios install {{ item }}"
  with_items: "{{ cs_scenarios_list }}"
  register: scenarios_install_result
  changed_when: "'overwrite' not in scenarios_install_result.stderr"
  when: cs_scenarios_list | length > 0

# parsers
- name: Crowdsec - remove parsers
  ansible.builtin.command:
    cmd: "cscli parsers remove {{ item }}"
  with_items: "{{ cs_parsers_remove_list }}"
  register: parsers_remove_result
  changed_when: "'systemctl reload crowdsec' in parsers_remove_result.stderr"
  when: cs_parsers_remove_list | length > 0

- name: Crowdsec - install parsers
  ansible.builtin.command:
    cmd: "cscli parsers install {{ item }}"
  with_items: "{{ cs_parsers_list }}"
  register: parsers_install_result
  changed_when: "'overwrite' not in parsers_install_result.stderr"
  when: cs_parsers_list | length > 0


# postoverflows
- name: Crowdsec - remove postoverflows
  ansible.builtin.command:
    cmd: "cscli postoverflows remove {{ item }}"
  with_items: "{{ cs_postoverflows_remove_list }}"
  register: postoverflows_remove_result
  changed_when: "'systemctl reload crowdsec' in postoverflows_remove_result.stderr"
  when: cs_postoverflows_remove_list | length > 0

- name: Crowdsec - install postoverflows
  ansible.builtin.command:
    cmd: "cscli postoverflows install {{ item }}"
  with_items: "{{ cs_postoverflows_list }}"
  register: postoverflows_install_result
  changed_when: "'overwrite' not in postoverflows_install_result.stderr"
  when: cs_postoverflows_list | length > 0

### Config files
- name: Crowdsec - enable/disable the Prometheus endpoint
  ansible.builtin.replace:
    path: "/etc/crowdsec/config.yaml"
    after: "prometheus:"
    regexp: 'enabled:.*$'
    replace: "{{ cs_prometheus_endpoint }}"
    backup: true

- name: Crowdsec - ajust ban time
  ansible.builtin.replace:
    path: "/etc/crowdsec/profiles.yaml"
    after: "- type: ban"
    regexp: 'duration: [0-9].*$'
    replace: "{{ cs_ban_duration }}"
    backup: true

# - name: Crowdsec - add jounalctl ssh to acquis.yaml
#  ansible.builtin.blockinfile:
#    path: /etc/crowdsec/acquis.d/ssh.yml
#    insertafter: EOF
#    block: "{{ cs_acquis_addon }}"
#    backup: true

- name: Crowdsec - cscli bash completion
  ansible.builtin.shell: |
    set -o pipefail
    cscli completion bash | tee /etc/bash_completion.d/cscli
  args:
    executable: /bin/bash
  register: bash_completion_result
  changed_when: "'# bash completion for' not in bash_completion_result.stdout"
  failed_when: "'Error' in bash_completion_result.stderr"

- name: Copy nginx-logs custom parser
  ansible.builtin.copy:
    src: nginx-logs.custom.yaml
    dest: /etc/crowdsec/parsers/s01-parse/nginx-logs.custom.yaml
    owner: root
    group: root
    mode: '0640'
- name: Crowdsec enable and start services
  ansible.builtin.service:
    name: crowdsec
    state: restarted
    enabled: true
  when:
    - enable_crowdsec | bool

- name: Setup crowdsecurity/whitelists
  ansible.builtin.template:
    src: whitelists.j2
    dest: /etc/crowdsec/parsers/s02-enrich/whitelists.custom.yaml
    owner: root
    group: root
    mode: '0600'

- name: Enrolls this machine to crowdsec console
  ansible.builtin.command: cscli console enroll --enable  custom,manual,tainted,context --name {{ crowdsec_enroll_name }} {{ crowdsec_enroll_key }}
  changed_when: false
  when: crowdsec_enroll_key | length > 0

- name: Crowdsec-firewall-bouncer enable  and  start services
  ansible.builtin.service:
    name: crowdsec-firewall-bouncer
    state: restarted
    enabled: true
  when:
    - crowdsec_install_firewall_bouncer | bool

### ------------ ####
# Muti server setup #

# - name: Crowdsec - LAPI server setup
#  ansible.builtin.include_tasks: lapi_server.yml
#  when:
#    - inventory_hostname in groups["cs_lapi_server"]

# - name: Crowdsec - LAPI agent setup
#  ansible.builtin.include_tasks: lapi_agent.yml
#  when:
#    - inventory_hostname in groups["cs_agents"]
