#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/common.sh"

ensure_output_dir

if [ ! -f "$LOCAL_ENV_TEST" ]; then
  echo "File $LOCAL_ENV_TEST not found. Create it from .env.test.example first." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$LOCAL_ENV_TEST"

vm_fqdn=$(remote_fqdn)
vm_name=$(remote_name)
test_site_prefix="${TEST_SITE_PREFIX:-portal}"
test_site_domain="${TEST_SITE_DOMAIN:-${test_site_prefix}.${vm_fqdn}}"
test_site_email="${TEST_SITE_EMAIL:-${BS_EMAIL_ADMIN_FOR_NOTIFY:-notify@example.com}}"
test_menu_full_user="${TEST_MENU_FULL_USER:-e2efull1}"
test_menu_default_domain="${TEST_MENU_DEFAULT_DOMAIN:-default.${vm_fqdn}}"
test_menu_link_default_domain="${TEST_MENU_LINK_DEFAULT_DOMAIN:-link-default.${vm_fqdn}}"
test_menu_full_domain="${TEST_MENU_FULL_DOMAIN:-full.${vm_fqdn}}"
test_menu_link_full_domain="${TEST_MENU_LINK_FULL_DOMAIN:-link-full.${vm_fqdn}}"
test_menu_full_path="/var/www/${test_menu_full_user}/${test_menu_full_domain}"
test_menu_enable_lets_encrypt="${TEST_MENU_ENABLE_LETS_ENCRYPT:-Y}"
test_menu_lets_encrypt_www="${TEST_MENU_LETS_ENCRYPT_WWW:-N}"
test_menu_redirect_to_https="${TEST_MENU_REDIRECT_TO_HTTPS:-N}"
test_menu_lets_encrypt_email="${TEST_MENU_LETS_ENCRYPT_EMAIL:-$test_site_email}"
test_menu_ftp_user="${TEST_MENU_FTP_USER:-e2eftp$(date +%H%M%S)}"
test_menu_ftp_password="${TEST_MENU_FTP_PASSWORD:-E2eFtpPass1234}"
test_menu_ftp_dir="${TEST_MENU_FTP_DIR:-${BS_PATH_DEFAULT_SITE:-/var/www/bitrix/default}}"
test_menu_smtp_account="${TEST_MENU_SMTP_ACCOUNT:-default}"
test_menu_smtp_from="${TEST_MENU_SMTP_FROM:-notify@example.com}"
test_menu_smtp_host="${TEST_MENU_SMTP_HOST:-smtp.example.com}"
test_menu_smtp_port="${TEST_MENU_SMTP_PORT:-587}"
test_menu_smtp_auth="${TEST_MENU_SMTP_AUTH:-Y}"
test_menu_smtp_login="${TEST_MENU_SMTP_LOGIN:-$test_menu_smtp_from}"
test_menu_smtp_password="${TEST_MENU_SMTP_PASSWORD:-}"
test_menu_smtp_auth_method="${TEST_MENU_SMTP_AUTH_METHOD:-auto}"
test_menu_smtp_tls="${TEST_MENU_SMTP_TLS:-Y}"
test_menu_smtp_starttls="${TEST_MENU_SMTP_STARTTLS:-Y}"
test_menu_smtp_recipient="${TEST_MENU_SMTP_RECIPIENT:-admin@example.com}"
test_menu_smtp_log_path="${TEST_MENU_SMTP_LOG_PATH:-${BS_PATH_USER_HOME_PREFIX:-/var/www}/${BS_PATH_USER_HOME:-bitrix}/msmtp_${test_menu_smtp_account}.log}"
test_menu_ntlm_site_path="${TEST_MENU_NTLM_SITE_PATH:-${BS_PATH_DEFAULT_SITE:-/var/www/bitrix/default}}"
test_menu_ntlm_ssl_lets_encrypt="${TEST_MENU_NTLM_SSL_LETS_ENCRYPT:-N}"
test_menu_ntlm_host="${TEST_MENU_NTLM_HOST:-$(printf '%.15s' "$vm_name")}"
test_menu_ntlm_name="${TEST_MENU_NTLM_NAME:-TEST}"
test_menu_ntlm_fqdn="${TEST_MENU_NTLM_FQDN:-TEST.LOCAL}"
test_menu_ntlm_dps="${TEST_MENU_NTLM_DPS:-10.0.0.10}"
test_menu_ntlm_user="${TEST_MENU_NTLM_USER:-Administrator}"
test_menu_ntlm_pass="${TEST_MENU_NTLM_PASS:-}"
test_menu_firewall_port="${TEST_MENU_FIREWALL_PORT:-54321/tcp}"
test_menu_firewall_zone="${TEST_MENU_FIREWALL_ZONE:-public}"

cp "$LOCAL_ENV_TEST" "$GENERATED_ENV_MENU"
{
  echo
  echo "# Generated by tests/runner/render_env.sh"
  printf 'TEST_VM_FQDN=%q\n' "$vm_fqdn"
  printf 'TEST_SITE_DOMAIN=%q\n' "$test_site_domain"
  printf 'TEST_SITE_EMAIL=%q\n' "$test_site_email"
  printf 'TEST_MENU_FULL_USER=%q\n' "$test_menu_full_user"
  printf 'TEST_MENU_DEFAULT_DOMAIN=%q\n' "$test_menu_default_domain"
  printf 'TEST_MENU_LINK_DEFAULT_DOMAIN=%q\n' "$test_menu_link_default_domain"
  printf 'TEST_MENU_FULL_DOMAIN=%q\n' "$test_menu_full_domain"
  printf 'TEST_MENU_LINK_FULL_DOMAIN=%q\n' "$test_menu_link_full_domain"
  printf 'TEST_MENU_FULL_PATH=%q\n' "$test_menu_full_path"
  printf 'TEST_MENU_ENABLE_LETS_ENCRYPT=%q\n' "$test_menu_enable_lets_encrypt"
  printf 'TEST_MENU_LETS_ENCRYPT_WWW=%q\n' "$test_menu_lets_encrypt_www"
  printf 'TEST_MENU_REDIRECT_TO_HTTPS=%q\n' "$test_menu_redirect_to_https"
  printf 'TEST_MENU_LETS_ENCRYPT_EMAIL=%q\n' "$test_menu_lets_encrypt_email"
  printf 'TEST_MENU_FTP_USER=%q\n' "$test_menu_ftp_user"
  printf 'TEST_MENU_FTP_PASSWORD=%q\n' "$test_menu_ftp_password"
  printf 'TEST_MENU_FTP_DIR=%q\n' "$test_menu_ftp_dir"
  printf 'TEST_MENU_SMTP_ACCOUNT=%q\n' "$test_menu_smtp_account"
  printf 'TEST_MENU_SMTP_FROM=%q\n' "$test_menu_smtp_from"
  printf 'TEST_MENU_SMTP_HOST=%q\n' "$test_menu_smtp_host"
  printf 'TEST_MENU_SMTP_PORT=%q\n' "$test_menu_smtp_port"
  printf 'TEST_MENU_SMTP_AUTH=%q\n' "$test_menu_smtp_auth"
  printf 'TEST_MENU_SMTP_LOGIN=%q\n' "$test_menu_smtp_login"
  printf 'TEST_MENU_SMTP_PASSWORD=%q\n' "$test_menu_smtp_password"
  printf 'TEST_MENU_SMTP_AUTH_METHOD=%q\n' "$test_menu_smtp_auth_method"
  printf 'TEST_MENU_SMTP_TLS=%q\n' "$test_menu_smtp_tls"
  printf 'TEST_MENU_SMTP_STARTTLS=%q\n' "$test_menu_smtp_starttls"
  printf 'TEST_MENU_SMTP_RECIPIENT=%q\n' "$test_menu_smtp_recipient"
  printf 'TEST_MENU_SMTP_LOG_PATH=%q\n' "$test_menu_smtp_log_path"
  printf 'TEST_MENU_NTLM_SITE_PATH=%q\n' "$test_menu_ntlm_site_path"
  printf 'TEST_MENU_NTLM_SSL_LETS_ENCRYPT=%q\n' "$test_menu_ntlm_ssl_lets_encrypt"
  printf 'TEST_MENU_NTLM_HOST=%q\n' "$test_menu_ntlm_host"
  printf 'TEST_MENU_NTLM_NAME=%q\n' "$test_menu_ntlm_name"
  printf 'TEST_MENU_NTLM_FQDN=%q\n' "$test_menu_ntlm_fqdn"
  printf 'TEST_MENU_NTLM_DPS=%q\n' "$test_menu_ntlm_dps"
  printf 'TEST_MENU_NTLM_USER=%q\n' "$test_menu_ntlm_user"
  printf 'TEST_MENU_NTLM_PASS=%q\n' "$test_menu_ntlm_pass"
  printf 'TEST_MENU_FIREWALL_PORT=%q\n' "$test_menu_firewall_port"
  printf 'TEST_MENU_FIREWALL_ZONE=%q\n' "$test_menu_firewall_zone"
} >> "$GENERATED_ENV_MENU"

printf '%s\n' "$GENERATED_ENV_MENU"
