---
- name: Delete the site {{ site }}
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Deliting site dir {{ full_path_site }}
      ansible.builtin.file:
        name: "{{ full_path_site }}"
        state: absent

    - block:

        - name: Installing of python3-pymysql
          ansible.builtin.apt:
            name: python3-pymysql
            state: present

        - name: Deliting data base {{ db_name }}
          community.mysql.mysql_db:
            name: "{{ db_name }}"
            state: absent

        - name: Deliting database user {{ db_user }}
          community.mysql.mysql_user:
            name: "{{ db_user }}"
            state: absent

        - name: Deliting cron task
          ansible.builtin.cron:
            name: Adding cron bitrix agents site {{ site }}
            user: "{{ user_server_sites }}"
            state: absent

      when: type == "full"

    - name: Rename Nginx config {{ site }}.conf
      ansible.builtin.file:
        name: "{{ path_nginx_sites_conf }}/{{ site }}.conf"
        state: absent

    - name: Delete nginx config link {{ site }}.conf
      ansible.builtin.file:
        name: "{{ path_nginx_sites_enabled }}/{{ site }}.conf"
        state: absent

    - name: Rename Apache config {{ site }}.conf
      ansible.builtin.file:
        name: "{{ path_apache_sites_conf }}/{{ site }}.conf"
        state: absent

    - name: Delete tmpfiles config
      ansible.builtin.file:
        dest: "/etc/tmpfiles.d/{{ site }}.conf"
        state: absent

    - name: Delete tmpfiles dirs
      ansible.builtin.file:
        dest: "{{ php_dirs }}"
        state: absent
      loop:
        - "/tmp/php_sessions/{{ site }}"
        - "/tmp/php_upload/{{ site }}"
      loop_control:
        loop_var: php_dirs

    - name: Restarting Nginx
      ansible.builtin.systemd:
        name: "{{ service_nginx_name }}"
        state: reloaded

    - name: Restarting Apache
      ansible.builtin.systemd:
        name: "{{ service_apache_name }}"
        state: reloaded
