---
- name: "Nginx ultimate bot blocker {{ bot_blocker_action }}"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - name: "Nginx ultimate bot blocker {{ bot_blocker_action }}"
      role: mitchellkrogza.nginx_ultimate_bad_bot_blocker
