---
- name: Setup initial software for environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars:
    bx_temporary_files_directory: "{{ path_sites }}/.bx_temp/{{ db_name }}/"
    marcelnijenhof_firewalld_allow_ports:
      - port: 8893/tcp
        immediate: false
      - port: 8894/tcp
        immediate: false
    marcelnijenhof_firewalld_allow_services:
      - service: https
        immediate: false
      - service: http
        immediate: false
      - service: ssh
        immediate: false
    mysql_databases:
      - name: "{{ db_name }}"
        collation: "{{ mysql_collation_server }}"
        encoding: "{{ mysql_character_set_server }}"
    mysql_users:
      - name: "{{ db_user }}"
        host: "localhost"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"

  roles:
    - infOpen.locales
    - marcelnijenhof.firewalld
    - systemd-overrides
    - geerlingguy.nginx
    - geerlingguy.nginx_config
    - geerlingguy.php-versions
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.mysql
    - geerlingguy.redis
    - bx_push_server
#    - tmpfiles
