---
- name: "AIDE {{ aide_action }}"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always
  roles:
    - name: "AIDE {{ aide_action }}"
      role: endebx_aide
