---
- name: Installing of a new full environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars:
    bx_temporary_files_directory: "{{ path_sites }}/.bx_temp/{{ db_name }}/"

  tasks:
    - name: Add cron agents
      ansible.builtin.include_tasks: "tasks/add_cron_agents.yaml"
      vars:
        path_file_run_cron: "{{ document_root }}{{ bx_cron_agents_path_file_after_document_root }}"
        user_site: "{{ user_server_sites }}"
        group_user_site: "{{ group_user_server_sites }}"
        logs_path_dir: "{{ bx_cron_logs_path_dir }}"
        logs_path_file: "{{ bx_cron_logs_path_file }}"

    - name: Creating directory from bitrix temporary files
      ansible.builtin.file:
        state: directory
        path: "{{ bx_temporary_files_directory }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"
        recurse: true

    - name: Fix owner of user_dir
      ansible.builtin.file:
        state: directory
        path: "{{ path_sites }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"
        recurse: true

    - name: Creating default site directory
      ansible.builtin.file:
        state: directory
        path: "{{ document_root }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"
        recurse: true

    - name: Creating default logs site directory
      ansible.builtin.file:
        state: directory
        path: "{{ document_root }}/logs"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"
        recurse: true

    - name: Creating array for deleting files
      ansible.builtin.set_fact:
        dell_files: "{{ delete_files.split(',') }}"

    - name: Deleting files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ dell_files }}"

    - name: Creating array with urls
      ansible.builtin.set_fact:
        urls: "{{ download_bitrix_install_files_new_site.split(',') }}"

    - name: Downloading Bitrix scripts
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ document_root }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"
        timeout: "{{ timeout_download_bitrix_install_files_new_site }}"
      with_items: "{{ urls }}"

    - name: Creating of downloaded file names array
      ansible.builtin.set_fact:
        file_names_download: "{{ urls | map('basename') | list }}"

    - name: Generating index.html using links of downloaded files
      ansible.builtin.template:
        dest: "{{ document_root }}/index.php"
        src: "roles/create_site/templates/site_full_tpl/index.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Creating directory bitrix/php_interface
      ansible.builtin.file:
        state: directory
        path: "{{ document_root }}/bitrix/php_interface"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_dirs }}"

    - name: Generating dbconn.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/php_interface/dbconn.php"
        src: "roles/create_site/templates/site_full_tpl/dbconn.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Generate crypto key
      ansible.builtin.set_fact:
        crypto_key: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=32') }}"

    - name: Read push-server config file
      ansible.builtin.slurp:
        src: "{{ push_server_config }}"
      register: push_config_content

    - name: Extract SECURITY_KEY and set push_key variable
      ansible.builtin.set_fact:
        push_key: "{{ push_config_content['content'] | b64decode | regex_search('SECURITY_KEY=\"([^\"]+)\"', '\\1') | first }}"

    - name: Generating .settings.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/.settings.php"
        src: "roles/create_site/templates/site_full_tpl/.settings.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Generating after_connect_d7.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/php_interface/after_connect_d7.php"
        src: "roles/create_site/templates/site_full_tpl/after_connect_d7.php.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Adding logrotate file
      ansible.builtin.template:
        src: "roles/create_site/templates/logrotate/logrotate.j2"
        dest: "/etc/logrotate.d/bx_{{ domain }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "644"

    ############## SITE FILES ##############
    - name: Adding .htaccess file
      ansible.builtin.copy:
        src: "roles/create_site/files/site_files/.htaccess"
        dest: "{{ document_root }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Get Nginx version
      ansible.builtin.command: nginx -v
      register: nginx_version_output
      changed_when: false

    - name: Extract Nginx version number
      ansible.builtin.set_fact:
        nginx_version: "{{ nginx_version_output.stderr | regex_search('\\d+\\.\\d+\\.\\d+') }}"

    - name: Copying nginx_files directory to /etc/{{ service_nginx_name }}
      ansible.builtin.copy:
        src: "roles/create_site/files/nginx_files/"
        dest: "/etc/{{ service_nginx_name }}/"
        owner: root
        group: root
        mode: '644'

    - name: Delete Astra Linux unsupported config
      ansible.builtin.file:
        path: "/etc/{{ service_nginx_name }}/custom_conf.d/section_http/{{ item }}"
        state: absent
      with_items:
        - brotli.conf
      when: ansible_os_family == 'Astra Linux'

    - name: Insert include line into http section of nginx.conf
      ansible.builtin.blockinfile:
        path: "/etc/{{ service_nginx_name }}/nginx.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          include custom_conf.d/section_http/*.conf;
        insertafter: "^http\\s*{"

    - name: Adding Nginx configuration file
      ansible.builtin.template:
        dest: "{{ path_nginx_sites_conf }}/{{ domain }}.conf"
        src: "roles/create_site/templates/nginx_conf/default.j2"
        owner: root
        group: root
        mode: '644'

    - name: Creating symbol link (site_enable) for Nginx configuration file
      ansible.builtin.file:
        src: "{{ path_nginx_sites_conf }}/{{ domain }}.conf"
        dest: "{{ path_nginx_sites_enabled }}/{{ domain }}.conf"
        state: link

    - name: Creating symbol link for Nginx rtc configuration file
      ansible.builtin.file:
        src: "{{ path_nginx_sites_conf }}/rtc.conf"
        dest: "{{ path_nginx_sites_enabled }}/rtc.conf"
        state: link

    - name: Adding symlink to Nginx site_settings directory
      ansible.builtin.file:
        src: "/etc/{{ service_nginx_name }}/custom_conf.d/site_settings"
        dest: "{{ path_nginx }}/site_settings"
        owner: root
        group: root
        state: link

    - name: Adding Nginx site_settings file
      ansible.builtin.template:
        src: "roles/create_site/templates/nginx_conf/bx_temp.j2"
        dest: "{{ path_nginx }}/site_settings/{{ domain }}/bx_temp.conf"
        owner: root
        group: root
        mode: '644'

    - name: Restarting Nginx
      ansible.builtin.systemd:
        name: "{{ service_nginx_name }}"
        state: restarted


    ############## APACHE ##############
    - name: Adding Apache configuration file
      ansible.builtin.template:
        dest: "{{ path_apache_sites_conf }}/{{ domain }}.conf"
        src: "roles/create_site/templates/apache_conf/default.j2"
        owner: root
        group: root
        mode: '644'

    - name: Creating symbol link (site_enable) for Apache configuration file
      ansible.builtin.file:
        src: "{{ path_apache_sites_conf }}/{{ domain }}.conf"
        dest: "{{ path_apache_sites_enabled }}/{{ domain }}.conf"
        state: link

    - name: Restarting Apache
      ansible.builtin.systemd:
        name: "{{ service_apache_name }}"
        state: restarted

    ############## PHP-FPM ##############
    - name: Setup PHP settings
      ansible.builtin.include_role:
        name: tmpfiles

# Change site user for connection SSH
    - name: Installing of python3-passlib
      ansible.builtin.apt:
        name: python3-passlib
        state: present

    - name: Creating directory .ssh
      ansible.builtin.file:
        path: "{{ path_sites }}/.ssh"
        state: directory
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: '0700'

    - name: Generating SSH key
      ansible.builtin.command: ssh-keygen -t ed25519 -b 2048 -f "{{ path_sites }}/.ssh/id_ed25519" -N ''
      args:
        creates: "{{ path_sites }}/.ssh/id_ed25519"

    - name: Creating file authorized_keys
      ansible.builtin.file:
        path: "{{ path_sites }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: '0600'

    - name: Change the rights to the directory
      ansible.builtin.file:
        path: "{{ path_sites }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        recurse: true

    - name: Change user for connecting SSH {{ user_server_sites }}
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: "^{{ user_server_sites }}:"
        line: "{{ user_server_sites }}:x:33:33:{{ group_user_server_sites }}:{{ path_sites }}:/bin/bash"
        state: present
      when: user_server_sites == 'www-data'

    - name: Delete html directory
      ansible.builtin.file:
        path: "/var/www/html"
        state: absent
      when: user_server_sites != 'www-data'

    - name: Setting password from user {{ user_server_sites }}
      ansible.builtin.user:
        name: "{{ user_server_sites }}"
        password: "{{ site_user_password | password_hash('sha512', 'passlib') }}"
