---
- name: "Postgresql {{ postgresql_action }}"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always
    - name: Add pin-priority rules for apt.postgresql.org
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/postgresql-pin
        content: |
          Package: *
          Pin: origin apt.postgresql.org
          Pin-Priority: 1000
        create: true
        mode: '0644'
        owner: root
        group: root
      when: ansible_facts_lsb_id is defined and ansible_facts_lsb_id == 'Astra'
      tags: always
    - name: Install gcc
      ansible.builtin.apt:
        name: gcc
        state: present
      when: postgresql_action == "INSTALL"
  roles:
    - name: "Postgresql {{ postgresql_action }}"
      role: claranet.postgresql

  post_tasks:
    - name: Remove gcc
      ansible.builtin.apt:
        name: gcc
        state: absent
        autoremove: true
