---
- name: Reset passwords
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars:
    bx_push_server_user: "{{ user_server_sites }}"
    bx_push_server_group: "{{ group_user_server_sites }}"
    bx_temporary_files_directory: "{{ path_sites }}/.bx_temp/{{ db_name }}/"
    mysql_databases:
      - name: "{{ db_name }}"
        collation: "{{ mysql_collation_server }}"
        encoding: "{{ mysql_character_set_server }}"
    mysql_users:
      - name: "{{ db_user }}"
        host: "localhost"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always

  tasks:
    - name: Reconfigure mysql
      ansible.builtin.include_role:
        name: geerlingguy.mysql

    - name: Reconfigure php
      ansible.builtin.include_role:
        name: geerlingguy.php

    - name: Generating dbconn.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/php_interface/dbconn.php"
        src: "roles/create_site/templates/site_full_tpl/dbconn.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Generate crypto key
      ansible.builtin.set_fact:
        crypto_key: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=32') }}"

    - name: Generate random string for push_key
      ansible.builtin.set_fact:
        bx_push_server_push_key: "{{ lookup('community.general.random_string', length=128, digits=true, special=false) }}"

    - name: Configure push-server
      ansible.builtin.template:
        src: roles/bx_push_server/templates/push-server-multi-config.j2
        dest: "/etc/default/push-server-multi"
        mode: '0644'
        force: true

    - name: Generate configs
      ansible.builtin.command: "/usr/local/bin/push-server-multi configs {{ item }}"
      loop:
        - pub
        - sub
      changed_when: false

    - name: Extract SECURITY_KEY and set push_key variable
      ansible.builtin.set_fact:
        push_key: "{{ bx_push_server_push_key }}"

    - name: Generating .settings.php file
      ansible.builtin.template:
        dest: "{{ document_root }}/bitrix/.settings.php"
        src: "roles/create_site/templates/site_full_tpl/.settings.j2"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: "{{ permissions_sites_files }}"

    - name: Delete old ssh-keys
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ path_sites }}/.ssh/id_ed25519"
        - "{{ path_sites }}/.ssh/id_ed25519.pub"

    - name: Generating SSH key
      ansible.builtin.command: ssh-keygen -t ed25519 -b 2048 -f "{{ path_sites }}/.ssh/id_ed25519" -N ''
      args:
        creates: "{{ path_sites }}/.ssh/id_ed25519"

    - name: Creating file authorized_keys
      ansible.builtin.file:
        path: "{{ path_sites }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        mode: '0600'

    - name: Change the rights to the directory
      ansible.builtin.file:
        path: "{{ path_sites }}"
        owner: "{{ user_server_sites }}"
        group: "{{ group_user_server_sites }}"
        recurse: true

    - name: Setting password for user {{ user_server_sites }}
      ansible.builtin.user:
        name: "{{ user_server_sites }}"
        password: "{{ site_user_password | password_hash('sha512', 'passlib') }}"
