---
- name: "Setup basic auth"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always
  roles:
    - name: Setup basic auth
      role: geerlingguy.htpasswd
