---
- name: "Setup repos"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always
  roles:
    - name: Setup Debian repos for Astra Linux
      role: setup_tmp_debian_repositories_for_astra
