---
- name: Setup deadsnakes/ppa
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always

    - name: Set facts for Debian bookworm
      ansible.builtin.set_fact:
        ansible_facts: "{{ ansible_facts | combine({'distribution_release': 'jammy'}) }}"
        ansible_distribution_release: "jammy"
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_release == 'bookworm'

    - name: Set facts for Debian trixie
      ansible.builtin.set_fact:
        ansible_facts: "{{ ansible_facts | combine({'distribution_release': 'noble'}) }}"
        ansible_distribution_release: "noble"
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_release == 'trixie'

  tasks:
    - name: Install deadsnakes PPA
      when: deadsnakes_action == "INSTALL"
      block:
        - name: Make pin-priority file for ppa.launchpadcontent.net
          ansible.builtin.blockinfile:
            path: /etc/apt/preferences.d/10-ppa.pref
            block: |
              Package: *
              Pin: origin ppa.launchpadcontent.net
              Pin-Priority: 10
            create: true
            owner: root
            group: root
            mode: "0644"
          when: ansible_distribution == "Debian"

        - name: Add deadsnakes/ppa key
          ansible.builtin.get_url:
            url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF23C5A6CF475977595C89F51BA6932366A755776&exact=on
            dest: /etc/apt/keyrings/deadsnakes.asc
            mode: "0644"
            owner: root
            group: root
          when:
            - ansible_os_family == "Debian"

        - name: Add deadsnakes/ppa
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/deadsnakes.asc] https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main"
            state: present
          when:
            - ansible_os_family == "Debian"

    - name: Delete deadsnakes PPA
      when: deadsnakes_action == "DELETE"
      block:
        - name: Remove pin-priority file for ppa.launchpadcontent.net
          ansible.builtin.file:
            path: /etc/apt/preferences.d/10-ppa.pref
            state: absent
          when: ansible_distribution == "Debian"

        - name: Remove deadsnakes/ppa key
          ansible.builtin.file:
            path: /etc/apt/keyrings/deadsnakes.asc
            state: absent
          when:
            - ansible_os_family == "Debian"

        - name: Remove deadsnakes/ppa
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/deadsnakes.asc] https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main"
            state: absent
          when:
            - ansible_os_family == "Debian"
