---
- name: Setup mydumper repo
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Add mydumper repo key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1D357EA7D10C9320371BDD0279EA15C0E82E34BA&exact=on
        dest: /etc/apt/keyrings/mydumper.asc
        mode: "0644"
        owner: root
        group: root
      when:
        - ansible_os_family == "Debian"

    - name: Add mydumper repo.
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/mydumper.asc] https://mydumper.github.io/mydumper/repo/apt/{{ ansible_distribution | lower }} ./"
        state: present
      when:
        - ansible_os_family == "Debian"

    - name: Update apt caches after repo is added (Debian).
      ansible.builtin.apt:
#        update_cache: true
        name:
          - mydumper
      when:
        - ansible_os_family == "Debian"
