---
- name: Setup setup_nginx_modules_repo
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always

  tasks:
    - name: Add nginx modules repo key
      ansible.builtin.get_url:
        url: https://yogsottot.github.io/ppa/yogsottot.asc
        dest: /etc/apt/keyrings/yogsottot.asc
        mode: "0644"
        owner: root
        group: root
      when:
        - ansible_os_family == "Debian"

    - name: Add nginx modules repo.
      ansible.builtin.deb822_repository:
        name: yogsottot_github_io_ppa_{{ ansible_distribution | lower }}
        types: deb
        uris: https://yogsottot.github.io/ppa/debian
        suites: '{{ ansible_distribution_release }}'
        components: main
        architectures: amd64
        signed_by: /etc/apt/keyrings/yogsottot.asc
        state: present
      when:
        - ansible_os_family == "Debian"

    - name: Install packages after repo is added (Debian).
      ansible.builtin.apt:
        update_cache: true
        name:
          - libnginx-mod-http-zip
      when:
        - ansible_os_family == "Debian"
