---
- name: Setup mydumper repo
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  pre_tasks:
    - name: Set facts for Astra Linux
      ansible.builtin.include_tasks: "tasks/set_facts_for_astra.yaml"
      tags: always

  tasks:
    - name: Add mydumper repo key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1D357EA7D10C9320371BDD0279EA15C0E82E34BA&exact=on
        dest: /etc/apt/keyrings/mydumper.asc
        mode: "0644"
        owner: root
        group: root
      when:
        - ansible_os_family == "Debian"

    - name: Add mydumper repo.
      ansible.builtin.deb822_repository:
        name: mydumper_github_io_mydumper_repo_apt_{{ ansible_distribution | lower }}
        types: deb
        uris: https://mydumper.github.io/mydumper/repo/apt/{{ ansible_distribution | lower }}
        suites: '{{ ansible_distribution_release }}'
        components: main
        architectures: amd64
        signed_by: /etc/apt/keyrings/mydumper.asc
        state: present
      when:
        - ansible_os_family == "Debian"

    - name: Update apt caches after repo is added (Debian).
      ansible.builtin.apt:
        update_cache: true
        name:
          - mydumper
      when:
        - ansible_os_family == "Debian"
