---
# tasks file for get_lets_encrypt_certificate
- name: Installing of Certbot
  ansible.builtin.apt:
    name: certbot
    state: latest
  when: ansible_os_family == 'Debian'

- name: Check if certbot exists
  ansible.builtin.stat:
    path: /usr/bin/certbot
  register: certbot_symlink

- name: Include task for astra
  ansible.builtin.include_tasks: "install_Astra Linux.yml"
  when: not certbot_symlink.stat.exists

- name: Ensure letsencrypt dir exists
  ansible.builtin.file:
    path: "/opt/letsencrypt/"
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Check for /opt/letsencrypt/ in acme_well_known.conf
  ansible.builtin.lineinfile:
    path: "/etc/{{ service_nginx_name }}/custom_conf.d/section_listen_http_and_https/acme_well_known.conf"
    regexp: '/opt/letsencrypt/'
    state: absent
  check_mode: true
  register: letsencrypt_check

- name: Set webroot-path variable
  ansible.builtin.set_fact:
    webroot_path: "{{ '/opt/letsencrypt/' if letsencrypt_check.found else path_site }}"

- name: Set certificate domain variable
  ansible.builtin.set_fact:
    letsencrypt_domain: "{{ ssl_lets_encrypt_domain | default(domain, true) | trim }}"

- name: Getting SSL certificate
  ansible.builtin.shell: |
        certbot certonly \
          --webroot \
          --webroot-path {{ webroot_path }} \
          --non-interactive \
          --agree-tos \
          --expand \
          --allow-subset-of-names \
          --deploy-hook "systemctl reload nginx" \
          --email {{ email }} \
          -d {{ letsencrypt_domain }} \
          {% if is_www == 'Y' %}-d www.{{ letsencrypt_domain }}{% endif %}
  args:
    creates: /etc/letsencrypt/live/{{ letsencrypt_domain }}/fullchain.pem

- name: Searching domain directory
  ansible.builtin.find:
    paths: "{{ letsencrypt_live_dir }}"
    file_type: directory
    patterns: "{{ letsencrypt_domain }}*"
  register: found_directory_domain

- name: Saving founded directory in variable
  ansible.builtin.set_fact:
    cert_full_domain_directory: "{{ found_directory_domain.files | map(attribute='path') | list | first }}"

- name: Checking is default site
  ansible.builtin.set_fact:
    nginx_config: "{{ domain }}"
  when: default_full_path_site != path_site

- name: Checking is default site
  ansible.builtin.set_fact:
    nginx_config: "{{ default_domain }}"
  when: default_full_path_site == path_site

- name: Checking Nginx configuration file
  ansible.builtin.stat:
    path: "{{ path_nginx }}/site_settings/{{ nginx_config }}/ssl.conf"
  register: real_nginx_config_file

- name: Changing Nginx configuration
  block:
    - name: Setting variables
      ansible.builtin.set_fact:
        ssl_cert_full_path: "{{ cert_full_domain_directory }}/{{ file_fullchain }}"
        ssl_cert_key_full_path: "{{ cert_full_domain_directory }}/{{ file_privkey }}"
        ssl_trusted_certificate_full_path: "{{ cert_full_domain_directory }}/{{ file_chain }}"

    - name: Loading Nginx configuration
      when: cert_full_domain_directory != "" and real_nginx_config_file.stat.exists
      ansible.builtin.slurp:
        src: "{{ path_nginx }}/site_settings/{{ nginx_config }}/ssl.conf"
      register: nginx_conf_data

    - name: Check if old manual SSL block exists
      ansible.builtin.set_fact:
        old_ssl_block_found: "{{ (nginx_conf_data.content | b64decode) is search('### START PLEASE DONT DELETE OR EDIT THIS COMMENT MANAGED SSL CERTS') }}"

    - name: Remove old manual SSL blocks
      ansible.builtin.replace:
        path: "{{ path_nginx }}/site_settings/{{ nginx_config }}/ssl.conf"
        regexp: >-
          (?s)### START PLEASE DONT DELETE OR EDIT THIS COMMENT MANAGED SSL CERTS\..*?
          ### END PLEASE DONT DELETE OR EDIT THIS COMMENT MANAGED SSL CERTS\.
          YOU CAN MAKE EDITS BETWEEN THESE COMMENTS ###
        replace: ''
      when: old_ssl_block_found

    - name: Manage SSL block in Nginx config
      ansible.builtin.blockinfile:
        path: "{{ path_nginx }}/site_settings/{{ nginx_config }}/ssl.conf"
        marker: "### {mark} MANAGED SSL CERTS ###"
        block: |
          # HERE YOU CAN CONNECT YOUR CONFIG WITH AN SSL CERTIFICATE
          ## include ssl_conf/ssl_{{ letsencrypt_domain }}.conf;

          # DONT DELETE THIS PARAMETERS - MANAGED SSL CERTS FROM Lets Encrypt
          ssl_certificate {{ ssl_cert_full_path }};
          ssl_certificate_key {{ ssl_cert_key_full_path }};
          {% if ssl_trusted_certificate_full_path | default('') | trim != '' %}
          ssl_trusted_certificate {{ ssl_trusted_certificate_full_path }};
          {% endif %}

    - name: Restarting Nginx
      ansible.builtin.systemd:
        name: "{{ service_nginx_name }}"
        state: reloaded

- name: Creating of redirection HTTP to HTTPS enabled for the site {{ domain }}
  ansible.builtin.include_tasks: "tasks/redirect_http_to_https.yaml"
  when: redirect_to_https == "Y"
