---
# tasks file for settings_smtp_sites
- name: Adding wrapper SMTP SH script
  when: is_new_install_env is defined and is_new_install_env == 'Y'
  block:
    - name: Generating SH script
      ansible.builtin.template:
        src: "local_scripts/msmtp_wrapper.j2"
        dest: "{{ smtp_path_wrapp_script_sh }}"
        owner: "root"
        group: "root"
        mode: '0755'

- name: Adding SMTP settings the site {{ site }}
  when: is_actions_account is defined and is_actions_account == 'Y'
  block:
    - name: Installing MSMTP
      ansible.builtin.apt:
        name: msmtp
        state: present

    - name: Creating setting file
      ansible.builtin.lineinfile:
        line: ""
        path: "{{ smtp_file_sites_config }}"
        owner: "{{ smtp_file_user_config }}"
        group: "{{ smtp_file_group_user_config }}"
        mode: "{{ smtp_file_permissions_config }}"
        create: true
        state: present

#    - name: Creating symlink setting file
#      ansible.builtin.file:
#        src: "{{ smtp_file_sites_config }}"
#        dest: /etc/msmtprc
#        state: link
#        force: true
#        mode: '0644'

#    - name: Creating log file
#      ansible.builtin.lineinfile:
#        line: ""
#        path: "{{ log_path }}"
#        owner: "{{ smtp_file_user_log }}"
#        group: "{{ smtp_file_group_user_log }}"
#        mode: "{{ smtp_file_permissions_config }}"
#        create: true
#        state: present

    - name: Read the current content of the file
      ansible.builtin.slurp:
        src: "{{ smtp_file_sites_config }}"
      register: msmtprc_content

    - name: Comment lines between markers
      ansible.builtin.set_fact:
        new_msmtprc_content: |
          {%- set start = {'word': false} -%}
          {% for line in msmtprc_content.content | b64decode | split('\n') %}
            {%- set stripped_line = line.strip() -%}
            {%- if stripped_line.startswith('# smtp auto managed account '+account_name) -%}
              {%- if start.update({'word': true}) -%} {% endif -%}
            {%- elif start.word and stripped_line.startswith('# smtp auto managed account') -%}
              {%- if start.update({'word': false}) -%} {% endif -%}
            {%- endif -%}
            {%- if start.word -%}
                {%- if line.strip() -%}
                  {%- set line = stripped_line.replace('#', '') -%}
                  {%- set line = '# ' + line -%}
                {%- endif -%}
            {%- endif -%}
            {{ line }}
          {% endfor %}

    - name: Saving new SMTP configuration
      ansible.builtin.copy:
        content: "{{ new_msmtprc_content }}"
        dest: "{{ smtp_file_sites_config }}"
        mode: '0644'

#    - name: Decode msmtprc_content.content
#      ansible.builtin.set_fact:
#        decoded_content: "{{ msmtprc_content.content | b64decode }}"

#    - name: Check if config contains 'account default' line and set account_default variable
#      ansible.builtin.set_fact:
#        account_default: >-
#          {% if 'account default' in decoded_content %}
#            {% set default_account = decoded_content | regex_search('account default\\s*(\\S+)', '\\1') %}
#            {% if default_account is not none and default_account | length > 0 %}
#              {% set default_account_value = default_account | first | trim %}
#              {% if default_account_value == account_name %}
#                Y
#              {% else %}
#                N
#              {% endif %}
#            {% else %}
#              N  # If the regex didn't return a valid match
#            {% endif %}
#          {% else %}
#            Y
#          {% endif %}

#    - name: Apply trim to account_default
#      ansible.builtin.set_fact:
#        account_default: "{{ account_default | trim }}"

    - name: Add new block configuration in SMTP config file
      ansible.builtin.blockinfile:
        marker: ''
        path: "{{ smtp_file_sites_config }}"
        mode: '0644'
        block: |
          # smtp auto managed account {{ account_name }}
          account {{ account_name }}
          logfile {{ log_path }}
          logfile_time_format "%Y-%m-%d %H:%M:%S"
          timeout {{ smtp_timeout }}
          host {{ smtp_host }}
          port {{ smtp_port }}
          from {{ email_from }}
          aliases /etc/aliases
          set_from_header on
          remove_bcc_headers on
          {% if is_auth == 'Y' %}
          {% if authentication_method == 'auto' %}
          auth on
          {% else %}
          auth {{ authentication_method }}
          {% endif %}
          user {{ login }}
          password {{ password }}
          {% else %}
          auth off
          {% endif %}

          {% if enable_TLS == 'Y' %}
          tls on
          {% else %}
          tls off
          {% endif %}
          tls_certcheck off
          tls_starttls off
        insertafter: EOF

- block:
    - name: Read the current content of the file
      ansible.builtin.slurp:
        src: "{{ smtp_file_sites_config }}"
      register: msmtprc_content

    - name: Read lines between markers
      ansible.builtin.set_fact:
        new_msmtprc_content: |
          {%- set start = {'word': false} -%}
          {%- for line in msmtprc_content.content | b64decode | split('\n') -%}
            {%- set stripped_line = line.strip() -%}
            {%- if stripped_line.startswith('# smtp auto managed account '+account_name) -%}
              {%- if start.update({'word': true}) -%} {% endif -%}
            {%- elif start.word and stripped_line.startswith('# smtp auto managed account') -%}
              {%- if start.update({'word': false}) -%} {% endif -%}
            {%- endif -%}
            {%- if start.word -%}
                {% if line.strip() and not stripped_line.startswith('#') %}
                  {{ line }}
                {% endif %}
            {%- endif -%}
          {%- endfor -%}

    - name: Print the content of the file
      ansible.builtin.debug:
        msg: "start_parse {{ new_msmtprc_content }} end_parse"
  when: print_account is defined and print_account == 'Y'
