---
# tasks file for install_or_delete_sphinx
- name: Installing Sphinx
  when: sphinx_action == 'INSTALL'
  block:
    - name: Installing Sphinx
      ansible.builtin.apt:
        name: sphinxsearch
        state: present

    - name: Copying config to /etc/sphinxsearch/sphinx.conf
      ansible.builtin.copy:
        src: "sphinxsearch/"
        dest: "/etc/sphinxsearch/"
        owner: root
        group: root
        mode: "0755"

    - name: Ensure php tmp dirs exist
      ansible.builtin.copy:
        dest: "/etc/tmpfiles.d/sphinx.conf"
        src: sphinx_tmpfiles.conf
        backup: true
        mode: "0640"

    - name: Create tmpfiles
      ansible.builtin.command: systemd-tmpfiles --create
      changed_when: true

    - name: Restarting sphinxsearch
      ansible.builtin.systemd:
        name: "sphinxsearch"
        state: restarted
        enabled: true

- name: Deleting Sphinx
  when: sphinx_action == 'DELETE'
  block:
    - name: Deleting Sphinx
      ansible.builtin.apt:
        name: sphinxsearch
        state: absent
