# make it separate fo each site
#map  $http_referer       $frame_options  {
#     "~^https?:\/\/([^\/]+\.)?(webvisor\.(com|org))"  "";
#     "~^https?:\/\/([^\/]+\.)?(yandex\.com)"          "";
#     "~^https?:\/\/([^\/]+\.)?(metri[ck]a\.yandex\.(com|ru|az|by|co\.il|com\.am|com\.ge|com\.tr|ee|fr|kg|kz|lt|lv|md|tj|tm|uz))" "";
#     default                 "SAMEORIGIN";
# }
