---
- name: Ensure configuration directories exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    follow: true
    mode: "0755"
  with_items:
    - "{{ php_conf_paths | flatten }}"
    - "{{ php_extension_conf_paths | flatten }}"

- name: Place PHP configuration file in place. # noqa name[casing]
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ item }}/php.ini"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ php_conf_paths }}"
  notify: restart webserver
  when: php_use_managed_ini

- name: Find all xdebug.ini files with pattern *-xdebug.ini
  ansible.builtin.find:
    paths: "{{ php_extension_conf_paths }}"
    patterns: "*-xdebug.ini"
    file_type: link
  register: xdebug_files

- name: Delete found xdebug.ini files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ xdebug_files.files }}"
  notify: restart webserver

- name: Place PHP configuration file in place. # noqa name[casing]
  ansible.builtin.template:
    src: bitrixenv.ini.j2
    dest: "{{ item }}/bitrixenv.ini"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ php_extension_conf_paths }}"
  notify: restart webserver
  when: php_use_managed_bitrixenv_ini

- name: Make z_bx_custom.ini file
  ansible.builtin.file:
    path: "/etc/php/{{ php_default_version_debian }}/cli/conf.d/z_bx_custom.ini"
    state: touch
    owner: root
    group: root
    mode: "0644"
  when: php_use_managed_bitrixenv_ini

- name: Adding symlink to z_bx_custom.ini
  ansible.builtin.file:
    src: "/etc/php/{{ php_default_version_debian }}/cli/conf.d/z_bx_custom.ini"
    dest: "/etc/php/{{ php_default_version_debian }}/fpm/conf.d/z_bx_custom.ini"
    owner: root
    group: root
    state: link
  when: php_use_managed_bitrixenv_ini

- name: Make sessions settings file
  ansible.builtin.blockinfile:
    path: "/etc/php/{{ php_default_version_debian }}/cli/conf.d/sessions_settings.ini"
    marker: "; {mark} {{ document_root }} "
    block: |
      [PATH={{ document_root }}]
      session.save_path = {{ php_session_save_path }}
      upload_tmp_dir = {{ php_upload_tmp_dir }}
      sendmail_path = /usr/local/bin/msmtp_wrapper.sh {{ domain }}
    create: true
    owner: root
    group: root
    mode: "0644"
  when: not php_use_managed_bitrixenv_ini
  notify: restart php-fpm

- name: Adding symlink to sessions settings file
  ansible.builtin.file:
    src: "/etc/php/{{ php_default_version_debian }}/cli/conf.d/sessions_settings.ini"
    dest: "/etc/php/{{ php_default_version_debian }}/fpm/conf.d/sessions_settings.ini"
    owner: root
    group: root
    state: link
  when: not php_use_managed_bitrixenv_ini
  notify: restart php-fpm
  with_items: "{{ php_extension_conf_paths }}"

- name: Make directory for logs
  ansible.builtin.file:
    path: /var/log/php-fpm/
    state: directory
    recurse: true
    owner: "{{ php_fpm_pool_user }}"
    group: "{{ php_fpm_pool_group }}"
    mode: "0777"
