---
- name: Ensure configuration path exist
  ansible.builtin.file:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/"
    state: directory
    owner: root
    group: root
    mode: "0644"
  loop: "{{ systemd_overrides_unit }}"

- name: Ensure configuration
  ansible.builtin.template:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/z_override.conf"
    src: z_override.conf.j2
    owner: root
    group: root
    mode: "0644"
  loop: "{{ systemd_overrides_unit }}"

- name: Daemon_reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart php{{ php_default_version_debian }}-fpm (temp, fix https://codeberg.org/oerdnj/deb.sury.org/issues/114)
  ansible.builtin.systemd:
    name: php{{ php_default_version_debian }}-fpm
    state: restarted
