---
rkhunter_additional_config:
  - ALLOWHIDDENDIR=/etc/.hg
  - ALLOWHIDDENFILE=/etc/.hgignore
  - ALLOWHIDDENDIR=/dev/shm/byobu-*/.last.tmux
  - ALLOWDEVFILE=/dev/shm/byobu-*-????????/.last.tmux/*
  - ALLOWDEVFILE=/dev/shm/byobu-*-????????/*/*
  - ALLOWDEVFILE=/dev/shm/byobu-*-????????/*
  - ALLOWDEVFILE=/dev/shm/sem.mp-????????
  - ALLOWDEVFILE=/dev/shm/PostgreSQL.??????????
  - ALLOWDEVFILE=/dev/shm/PostgreSQL.*
  - ALLOWDEVFILE=/dev/shm/mongoc-??????
  - ALLOWDEVFILE=/dev/shm/sem.netdata_sem_cgroup_ebpf
  - ALLOWDEVFILE=/dev/shm/netdata_shm_cgroup_ebpf
