---
# Setup tasks.
- name: Setup tasks
  ansible.builtin.include_tasks:
    file: >-
      {{ 'setup-Astra Linux.yml'
         if ansible_facts_lsb_id is defined and ansible_facts_lsb_id == 'Astra'
         else 'setup-' ~ ansible_os_family ~ '.yml' }}
