---
- name: Set the correct opcache filename (Ubuntu/Debian).
  ansible.builtin.set_fact:
    php_opcache_conf_filename: "10-opcache.ini"

- name: Ensure dirmngr is installed (gnupg dependency).
  ansible.builtin.apt:
    name: dirmngr
    state: present

- name: Add ppa:ondrej/php key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6&exact=on
    dest: /etc/apt/keyrings/ondrej.asc
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"

- name: Add ppa:ondrej/php
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/ondrej.asc] http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_facts.distribution_release }} main"
    state: present
  when: ansible_distribution == "Ubuntu"

# Debian-specific tasks.
- name: Add dependencies for PHP versions (Debian).
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's apt key (Debian).
  ansible.builtin.get_url:
    url: https://mirror.hoztnode.net/mirrors/deb.sury.org/apt.gpg
    dest: /etc/apt/keyrings/deb.sury.org.gpg
    mode: "0644"
    owner: root
    group: root
  when: ansible_distribution == "Debian"

- name: Add Ondrej Sury's repo (Debian).
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/deb.sury.org.gpg] https://mirror.hoztnode.net/mirrors/deb.sury.org/php {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  when: ansible_distribution == "Debian"

- name: Update apt caches after repo is added (Debian).
  ansible.builtin.apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
    - ansible_distribution == "Debian"
  tags: ['skip_ansible_lint']
