---
- name: Include deps list
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install deps
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    "{{ bashrc_packages }}"
  environment:
    NEEDRESTART_MODE: automatically

- name: Needrestart setup
  ansible.builtin.include_tasks: needrestart.yml

- name: Bashrc setup
  ansible.builtin.include_tasks: bashrc.yml

- name: Byobu setup
  ansible.builtin.include_tasks: byobu.yml

- name: Htop setup
  ansible.builtin.include_tasks: htop.yml

- name: Lnav setup
  ansible.builtin.include_tasks: lnav.yml

- name: Liquidprompt setup
  ansible.builtin.include_tasks: liquidprompt.yml
